"""
桌面小工具樣式常數
重用主程式的 COLORS 並加入小工具專用樣式
"""
from gui.widgets import (
    COLORS, SERVICE_ACCENTS, format_tokens, ProgressBar,
    UI_FONT, MONO_FONT,
    FONT_TITLE, FONT_HERO, FONT_HERO_UNIT, FONT_HERO_LABEL,
    FONT_KV_LABEL, FONT_KV_VALUE, FONT_BAR_LABEL, FONT_BAR_PCT,
    FONT_BAR_DETAIL, FONT_RESET_PILL, FONT_BADGE, FONT_TIMESTAMP,
)

# ── 小工具專用文字色 ──────────────────────────────────────────────────────
WIDGET_LABEL   = "#71717a"
WIDGET_TEXT    = "#fafafa"
WIDGET_SUBTEXT = "#52525b"

# ── 小工具視窗設定 ────────────────────────────────────────────────────────
WIDGET_WIDTH = 380
WIDGET_MIN_HEIGHT = 400

# ── 精簡版卡片設定 ────────────────────────────────────────────────────────
COMPACT_CARD_PAD_X = 10
COMPACT_CARD_PAD_Y = 4

# ── 精簡版字型（比主視窗小 2pt）─────────────────────────────────────────
COMPACT_FONT_TITLE      = (UI_FONT, 9, "bold")
COMPACT_FONT_HERO       = (MONO_FONT, 22, "bold")
COMPACT_FONT_HERO_UNIT  = (MONO_FONT, 12)
COMPACT_FONT_HERO_LABEL = (UI_FONT, 7, "bold")
COMPACT_FONT_KV_LABEL   = (UI_FONT, 8)
COMPACT_FONT_KV_VALUE   = (MONO_FONT, 9, "bold")
COMPACT_FONT_BAR_LABEL  = (UI_FONT, 8)
COMPACT_FONT_BAR_PCT    = (MONO_FONT, 8, "bold")
COMPACT_FONT_BAR_DETAIL = (MONO_FONT, 7)
COMPACT_FONT_RESET_PILL = (MONO_FONT, 7, "bold")
COMPACT_FONT_BADGE      = (UI_FONT, 7)
COMPACT_FONT_TIMESTAMP  = (MONO_FONT, 7)

__all__ = [
    "COLORS", "SERVICE_ACCENTS", "format_tokens", "ProgressBar",
    "UI_FONT", "MONO_FONT",
    "FONT_TITLE", "FONT_HERO", "FONT_HERO_UNIT", "FONT_HERO_LABEL",
    "FONT_KV_LABEL", "FONT_KV_VALUE", "FONT_BAR_LABEL", "FONT_BAR_PCT",
    "FONT_BAR_DETAIL", "FONT_RESET_PILL", "FONT_BADGE", "FONT_TIMESTAMP",
    "WIDGET_WIDTH", "WIDGET_MIN_HEIGHT",
    "WIDGET_LABEL", "WIDGET_TEXT", "WIDGET_SUBTEXT",
    "COMPACT_CARD_PAD_X", "COMPACT_CARD_PAD_Y",
    "COMPACT_FONT_TITLE", "COMPACT_FONT_HERO", "COMPACT_FONT_HERO_UNIT",
    "COMPACT_FONT_HERO_LABEL", "COMPACT_FONT_KV_LABEL", "COMPACT_FONT_KV_VALUE",
    "COMPACT_FONT_BAR_LABEL", "COMPACT_FONT_BAR_PCT", "COMPACT_FONT_BAR_DETAIL",
    "COMPACT_FONT_RESET_PILL", "COMPACT_FONT_BADGE", "COMPACT_FONT_TIMESTAMP",
]
